// Names for common colours according to https://htmlcolorcodes.com/color-names/

export const colourList = {
// Red Family
    "CD5C5C": "Indian Red",
    "F08080": "Light Coral",
    "FA8072": "Salmon",
    "E9967A": "Dark Salmon",
    "DC143C": "Crimson",
    "FF0000": "Red",
    "B22222": "Fire Brick",
    "8B0000": "Dark Red",

// Pink Family
    "FFC0CB": "Pink",
    "FFB6C1": "Light Pink",
    "FF69B4": "Hot Pink",
    "FF1493": "Deep Pink",
    "C71585": "Medium Violet Red",
    "DB7093": "Pale Violet Red",

// Orange Family
    "FFA07A": "Light Salmon",
    "FF7F50": "Coral",
    "FF6347": "Tomato",
    "FF4500": "Orange Red",
    "FF8C00": "Dark Orange",
    "FFA500": "Orange",

// Yellow Family
    "FFD700": "Gold",
    "FFFF00": "Yellow",
    "FFFFE0": "Light Yellow",
    "FFFACD": "Lemon Chiffon",
    "FAFAD2": "Light Golden Rod Yellow",
    "FFEFD5": "Papaya Whip",
    "FFE4B5": "Moccasin",
    "FFDAB9": "Peach Puff",
    "EEE8AA": "Pale Golden Rod",
    "F0E68C": "Khaki",
    "BDB76B": "Dark Khaki",

// Puurple Family
    "E6E6FA": "Lavender",
    "D8BFD8": "Thistle",
    "DDA0DD": "Plum",
    "EE82EE": "Violet",
    "DA70D6": "Orchid",
    "FF00FF": "Magenta",
    "BA55D3": "Medium Orchid",
    "9370DB": "Medium Purple",
    "663399": "Rebecca Purple",
    "8A2BE2": "Blue Violet",
    "9400D3": "Dark Violet",
    "9932CC": "Dark Orchid",
    "8B008B": "Dark Magenta",
    "800080": "Purple",
    "4B0082": "Indigo",
    "6A5ACD": "Slate Blue",
    "483D8B": "Dark Slate Blue",
    "7B68EE": "Medium Slate Blue",

// Green Family
    "ADFF2F": "Green Yellow",
    "7FFF00": "Chart Reuse",
    "7CFC00": "Lawn Green",
    "00FF00": "Lime",
    "32CD32": "Lime Green",
    "98FB98": "Pale Green",
    "90EE90": "Light Green",
    "00FA9A": "Medium Spring Green",
    "00FF7F": "Spring Green",
    "3CB371": "Medium Sea Green",
    "2E8B57": "Sea Green",
    "228B22": "Forest Green",
    "008000": "Green",
    "006400": "Dark Green",
    "9ACD32": "Yellow Green",
    "6B8E23": "Olive Drab",
    "808000": "Olive",
    "556B2F": "Dark Olive Green",
    "66CDAA": "Medium Aqua Marine",
    "8FBC8B": "Dark Sea Green",
    "20B2AA": "Light Sea Green",
    "008B8B": "Dark Cyan",
    "008080": "Teal",

// Blue Family
    "00FFFF": "Cyan",
    "E0FFFF": "Light Cyan",
    "AFEEEE": "Pale Turquoise",
    "7FFFD4": "Aqua Marine",
    "40E0D0": "Turquiose",
    "48D1CC": "Medium Turquiose",
    "00CED1": "Dark Turquiose",
    "5F9EA0": "Cadet Blue",
    "4682B4": "Steel Blue",
    "B0C4DE": "Light Steel Blue",
    "B0E0E6": "Powder Blue",
    "ADD8E6": "Light Blue",
    "87CEEB": "Sky Blue",
    "87CEFA": "Light Sky Blue",
    "00BFFF": "Deep Sky Blue",
    "1E90FF": "Dodger Blue",
    "6495ED": "Corn Flower Blue",
    "4169E1": "Royal Blue",
    "0000FF": "Blue",
    "0000CD": "Medium Blue",
    "00008B": "Dark Blue",
    "000080": "Navy",
    "191970": "Midnight Blue",

// Brown Family
    "FFF8DC": "Corn Silk",
    "FFEBCD": "Blanched Almond",
    "FFE4C4": "Bisque",
    "FFDEAD": "Navajo White",
    "F5DEB3": "Wheat",
    "DEB887": "BurlyWood",
    "D2B48C": "Tan",
    "BC8F8F": "Rosy Brown",
    "F4A460": "Sandy Brown",
    "DAA520": "Golden Rod",
    "B8860B": "Dark Golden Rod",
    "CD853F": "Peru",
    "D2691E": "Chocolate",
    "8B4513": "Saddle Brown",
    "A0522D": "Sienna",
    "A52A2A": "Brown",
    "800000": "Maroon",

// White Family
    "FFFFFF": "White",
    "FFFAFA": "Snow",
    "F0FFF0": "Honey Drew",
    "F5FFFA": "Mint Cream",
    "F0FFFF": "Azure",
    "F0F8FF": "Alice Blue",
    "F8F8FF": "Ghost White",
    "F5F5F5": "White Smoke",
    "FFF5EE": "Sea Shell",
    "F5F5DC": "Beige",
    "FDF5E6": "Old Lace",
    "FFFAF0": "Floral White",
    "FFFFF0": "Ivory",
    "FAEBD7": "Antique White",
    "FAF0E6": "Linen",
    "FFF0F5": "Lavender Blush",
    "FFE4E1": "Misty Rode",

// Gray Family
    "DCDCDC": "Gains Boro",
    "D3D3D3": "Light Gray",
    "C0C0C0": "Silver",
    "A9A9A9": "Dark Gray",
    "808080": "Gray",
    "696969": "Dim Gray",
    "778899": "Light Slate Gray",
    "708090": "Slate Gray",
    "2F4F4F": "Dark Slate Gray",
    "000000": "Black",
};